// <auto-generated />
using System;
using ConsumidorPedidos.Data.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsumidorPedidos.Data.MySql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240904185358_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConsumidorPedidos.Model.Item", b =>
                {
                    b.Property<int>("CodigoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CodigoItem"));

                    b.Property<int?>("PedidoCodigoPedido")
                        .HasColumnType("int");

                    b.Property<float>("Preco")
                        .HasColumnType("float");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("CodigoItem");

                    b.HasIndex("PedidoCodigoPedido");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("ConsumidorPedidos.Model.Pedido", b =>
                {
                    b.Property<int>("CodigoPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CodigoPedido"));

                    b.Property<int>("CodigoCliente")
                        .HasColumnType("int");

                    b.HasKey("CodigoPedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ConsumidorPedidos.Model.Item", b =>
                {
                    b.HasOne("ConsumidorPedidos.Model.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoCodigoPedido");
                });

            modelBuilder.Entity("ConsumidorPedidos.Model.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
