// <auto-generated />
using System;
using ConsumidorPedidos.Data.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsumidorPedidos.Data.MySql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240905135628_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ConsumidorPedidos.Model.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("float")
                        .HasAnnotation("Relational:JsonPropertyName", "preco");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "produto");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "quantidade");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Item");

                    b.HasAnnotation("Relational:JsonPropertyName", "itens");
                });

            modelBuilder.Entity("ConsumidorPedidos.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "codigoPedido");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientCode")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:JsonPropertyName", "codigoCliente");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ConsumidorPedidos.Model.Item", b =>
                {
                    b.HasOne("ConsumidorPedidos.Model.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ConsumidorPedidos.Model.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
